#name: CI/CD with Docker and GitHub Actions

#on:
#  push:
#    branches:
#      - main 

#jobs:
#  build-and-push:
#    name: Build and Push Docker Images
#    runs-on: ubuntu-latest 

#    steps:
      # Step 1 : 檢出code
      #      - name: Checkout Code
      # uses: actions/checkout@v3

      # Step2: 登入 Docker Hub
      #- name: Login to Docker Hub
      # uses: docker/login-action@v2
      # with:
      #   username: ${{ secrets.DOCKER_USERNAME }}
      #   password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Step3: 建置後端映像並推送到 Docker Hub
      #- name: Build and Push Backend Image
      # run: |
      #    docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-repo:latest -f backend/Dockerfile .
      #    docker push ${{ secrets.DOCKER_USERNAME }}/backend-repo:latest
      
      # Step4: 建置前端映像並推送到 Docker Hub
      # - name: Build and Push Frontend Image
      #  run: |
      #    docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-repo:latest -f frontend/Dockerfile .
      #    docker push ${{ secrets.DOCKER_USERNAME }}/frontend-repo:latest
