name: Deploy to Aws EC2

on:
 push:
   branches:
     - main 

jobs:
 deploy:
   runs-on: ubuntu-latest 

   steps:
     #Step 1 : 檢出code
     - name: Checkout Code
       uses: actions/checkout@v3

     #Step 2 : 設定Docker環境
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     #Step 3 : 登入 Docker Hub
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
     #Step 4 : 建置後端映像並推送到 Docker Hub
     - name: Build and Push Backend Docker Image
       run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ./backend
         docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
      
     - name: Build and Push Frontend Docker Image
       run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest ./frontend
         docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

     #Step 5: 傳送docker-compose.yml 到 EC2
     - name: Transfer docker-compose.yml to EC2
       uses: appleboy/scp-action@v0.1.4
       with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "~/webonec2/"

     #Step 6: 使用 SSH 登入 EC2，並拉取更新的 Docker Images 及重啟服務
     - name: Deploy to EC2
       uses: appleboy/ssh-action@v1.0.0
       with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/webonec2/
            docker-compose down
            docker-compose pull
            docker-compose up -d

